run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true 
  disable:
    - execinquery
    - gomnd
    - depguard
    - exhaustruct
    - wsl
    - nlreturn
    - varnamelen
    - gofumpt
    - revive
    - forbidigo
    - gochecknoglobals
    - stylecheck


issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0


