run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - gocyclo
    - unparam
    - prealloc
    - unused
    - misspell
    - goconst
    - gocritic
    - gosec
    

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0


