name: gobase continuous integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    environment: development
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - run: make test
  coverage:
    runs-on: ubuntu-latest
    environment: development
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
  build:
    runs-on: ubuntu-latest
    environment: development
    needs: coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - run: make generate
      - run: make binary
  