name: gobase continuous integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: development
    
  build:
    runs-on: ubuntu-latest
    environment: development
    env:
      APP_NAME: gobase
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      VERSION: ${{ vars.VERSION }}
      BINARY_NAME: ${{ vars.BINARY_NAME }}
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      DIST_DIR: ${{ vars.DIST_DIR }}
      BUILD_TAGS: ${{ vars.BUILD_TAGS }}
      PORT: ${{ vars.PORT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - run: make setup
      - run: make build
      - run: make test
